import { ApifyClient } from 'apify-client';
import { supabase, getSetting } from '../db/supabase.js';
import { analyzeVideo } from './aiAnalyzer.js';

const APIFY_ACTOR = 'streamers/youtube-scraper';

async function getApifyClient() {
  const token = (await getSetting('apify_token')) || process.env.APIFY_TOKEN;
  if (!token) throw new Error('APIFY_TOKEN no configurado. Configúralo en Ajustes.');
  return new ApifyClient({ token });
}

function extractIdFromUrl(url) {
  if (!url) return null;
  const m = url.match(/(?:v=|\/shorts\/|youtu\.be\/)([\w-]{11})/);
  return m ? m[1] : null;
}

function parseDuration(d) {
  if (typeof d === 'number') return d;
  if (typeof d !== 'string') return null;
  const parts = d.split(':').map(Number);
  if (parts.some(isNaN)) return null;
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  return null;
}

function extractTranscript(item) {
  if (item.subtitles && Array.isArray(item.subtitles) && item.subtitles.length) {
    const first = item.subtitles[0];
    if (typeof first === 'string') return first;
    if (first.text) return first.text;
    if (first.plaintext) return first.plaintext;
    if (Array.isArray(first.segments)) {
      return first.segments.map((s) => s.text || s).join(' ');
    }
  }
  if (item.transcript) return item.transcript;
  return null;
}

async function upsertVideo(channelId, item) {
  const youtubeId = item.id || item.videoId || extractIdFromUrl(item.url);
  if (!youtubeId) return null;

  const { data: existing } = await supabase
    .from('videos')
    .select('id')
    .eq('youtube_id', youtubeId)
    .maybeSingle();

  let videoId, isNew = false;
  const url = item.url || `https://www.youtube.com/watch?v=${youtubeId}`;
  const fields = {
    title: item.title ?? null,
    description: item.text ?? item.description ?? null,
    published_at: item.date ?? item.publishedAt ?? null,
    duration_seconds: item.duration ? parseDuration(item.duration) : null,
    thumbnail_url: item.thumbnailUrl ?? null,
    last_scraped_at: new Date().toISOString(),
  };

  if (existing) {
    videoId = existing.id;
    await supabase.from('videos').update(fields).eq('id', videoId);
  } else {
    isNew = true;
    const { data: inserted, error } = await supabase
      .from('videos')
      .insert({
        channel_id: channelId,
        youtube_id: youtubeId,
        url,
        ...fields,
      })
      .select('id')
      .single();
    if (error) throw error;
    videoId = inserted.id;
  }

  // Snapshot histórico de métricas
  if (item.viewCount != null || item.likes != null || item.commentsCount != null) {
    await supabase.from('video_metric_snapshots').insert({
      video_id: videoId,
      views: item.viewCount ?? null,
      likes: item.likes ?? null,
      comments: item.commentsCount ?? null,
    });
  }

  // Transcripción
  const transcript = extractTranscript(item);
  if (transcript) {
    const { data: tExisting } = await supabase
      .from('video_transcripts')
      .select('id')
      .eq('video_id', videoId)
      .maybeSingle();
    if (!tExisting) {
      await supabase.from('video_transcripts').insert({
        video_id: videoId,
        language: item.subtitles?.[0]?.language || 'unknown',
        transcript,
        source: 'apify',
      });
    }
  }

  return { videoId, isNew };
}

export async function runScrape(channelId, trigger = 'manual') {
  const { data: channel, error: chErr } = await supabase
    .from('channels').select('*').eq('id', channelId).maybeSingle();
  if (chErr || !channel) throw new Error('canal no encontrado');

  const { data: cfg } = await supabase
    .from('scraper_config').select('*').eq('channel_id', channelId).maybeSingle();
  const maxVideos = cfg?.max_videos_per_run || 10;

  const { data: runRow, error: runErr } = await supabase
    .from('scraper_runs')
    .insert({ channel_id: channelId, status: 'running', trigger })
    .select('id')
    .single();
  if (runErr) throw runErr;
  const runId = runRow.id;

  try {
    const client = await getApifyClient();

    // Input estándar del actor streamers/youtube-scraper.
    // downloadSubtitles + preferAutoGeneratedSubtitles cubren videos sin captions oficiales.
    const input = {
      startUrls: [{ url: `https://www.youtube.com/${channel.handle}/videos` }],
      maxResults: maxVideos,
      maxResultsShorts: 0,
      maxResultStreams: 0,
      downloadSubtitles: true,
      preferAutoGeneratedSubtitles: true,
      subtitlesLanguage: 'any',
      subtitlesFormat: 'plaintext',
      saveSubsToKVS: false,
    };

    const run = await client.actor(APIFY_ACTOR).call(input);
    const { items } = await client.dataset(run.defaultDatasetId).listItems();

    let newCount = 0, updatedCount = 0;
    const newVideoIds = [];
    for (const it of items) {
      try {
        const r = await upsertVideo(channelId, it);
        if (r) {
          if (r.isNew) { newCount++; newVideoIds.push(r.videoId); }
          else updatedCount++;
        }
      } catch (e) {
        console.error('upsert fail', e.message);
      }
    }

    await supabase.from('scraper_runs').update({
      status: 'success',
      finished_at: new Date().toISOString(),
      videos_found: items.length,
      videos_new: newCount,
      videos_updated: updatedCount,
    }).eq('id', runId);

    // Análisis IA en background
    analyzeNewVideos(newVideoIds).catch((e) => console.error('analyze error', e));

    return { found: items.length, new: newCount, updated: updatedCount };
  } catch (e) {
    await supabase.from('scraper_runs').update({
      status: 'error',
      finished_at: new Date().toISOString(),
      error_message: String(e.message || e),
    }).eq('id', runId);
    throw e;
  }
}

async function analyzeNewVideos(videoIds) {
  for (const id of videoIds) {
    try { await analyzeVideo(id); }
    catch (e) { console.error('analyze', id, e.message); }
  }
}
