-- =========================================================
-- Pain Points seed (DESACTIVADO en este flujo)
-- =========================================================
-- Originalmente este archivo sembraba 10 pain points LATAM hardcoded.
-- El flujo correcto ahora es:
--   1) Scrapear y analizar videos (transcripts procesados con IA)
--   2) Botón "Extraer pain points" en la página /pain-points
--      → Claude analiza los emprendimientos, extrae pain points reales
--      → Investiga aplicabilidad LATAM con razonamiento + evidencia
--   3) Pain points "manuales" se pueden añadir desde la UI si hace falta
--
-- Si quisieras volver a ese seed manual, los 10 originales se pueden
-- añadir desde la UI con el formulario o restaurar este archivo desde
-- el git log (commit anterior).
SELECT 1; -- no-op para que el archivo sea ejecutable
